CREATE DATABASE USUARIOS;

CREATE TABLE ROL (
    ID_ROL INT PRIMARY KEY,
    NOMBRE VARCHAR(40));

CREATE TABLE USUARIO(
  ID_USUARIO INT PRIMARY KEY,
  ID_ROL INT,
  NOMBRE VARCHAR(40),
  ACTIVO CHAR(2));

ALTER TABLE USUARIO
ADD CONSTRAINT FK_usuario_rol
FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL);

INSERT INTO ROL (ID_ROL, NOMBRE) VALUES ('1' 'ADMINISTRADOR');
INSERT INTO ROL (ID_ROL, NOMBRE) VALUES ('2', 'AUDITOR');
INSERT INTO ROL (ID_ROL, NOMBRE) VALUES ('3', 'AUXILIAR');

INSERT INTO USUARIO(ID_USUARIO,ID_ROL, NOMBRE, ACTIVO) VALUES (1,2 , 'Camilo','SI');
INSERT INTO USUARIO(ID_USUARIO,ID_ROL, NOMBRE, ACTIVO) VALUES (2,1 , 'Carlos','NO');
INSERT INTO USUARIO(ID_USUARIO,ID_ROL, NOMBRE, ACTIVO) VALUES (3,3 , 'Sandra','SI');
